In [ ]:
import numpy as np
empty_array = np.empty((2,2))
print (empty_array)

[[4.87143841e-310 0.00000000e+000]
 [6.58136995e-310 4.87067457e-310]]


In [ ]:
import numpy as np
ones_array = np.ones((4,2))
print ((ones_array))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np
filled_array = np.full((4,2),7,dtype=int)
print(filled_array)

[[7 7]
 [7 7]
 [7 7]
 [7 7]]


In [ ]:
import numpy as np
zeros_array = np.zeros_like(filled_array)
print(zeros_array)


[[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
import numpy as np
ones_array = np.ones_like(filled_array)
print(ones_array)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
import numpy as np
new_list = [1,2,3,4]
new_array = np.array(new_list)
print(new_array)

[1 2 3 4]


In [ ]:
import numpy as np

original_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
ones_array = np.ones_like(original_array)
print(ones_array)

[[1 1 1]
 [1 1 1]]


In [ ]:
new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print(numpy_array)

[1 2 3 4]


problem:2

In [ ]:
import numpy as np
array_range = np.arange(10,50)
print(array_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
array_1d = np.arange(9)
matrix_3x3 = array_1d.reshape((3, 3))
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
random_array = np.random.random(30)
mean_value = random_array.mean()
print(mean_value)

0.45704389172524923


In [ ]:
random_array = np.random.rand(10, 10)
min_value = random_array.min()
max_value = random_array.max()
print(min_value, max_value)

0.017477283233742757 0.9995452520689551


In [ ]:
zeros_array = np.zeros(10)
zeros_array[4] = 1
print(zeros_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [ ]:
shape = (5,5)
array_2d = np.ones(shape, dtype=int)
array_2d[1:-1, 1:-1] = 0
print(array_2d)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem :3


In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

addition = x + y
print("Addition:\n", addition)

subtraction = x - y
print("Subtraction:\n", subtraction)

multiply_x = x * 2
multiply_y = y * 3
print("x multiplied by 2:\n", multiply_x)
print("y multiplied by 3:\n", multiply_y)

square_x = np.square(x)
square_y = np.square(y)
print("Square of x:\n", square_x)
print("Square of y:\n", square_y)

dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)
print("Dot product of v and w:", dot_v_w)
print("Dot product of x and v:\n", dot_x_v)
print("Dot product of x and y:\n", dot_x_y)

concat_xy = np.concatenate((x, y), axis=0)
concat_vw = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("Concatenated x and y:\n", concat_xy)
print("Concatenated v and w:\n", concat_vw)

try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenated x and v:\n", concat_xv)
except ValueError as e:
    print("Error:", e)

Addition:
 [[ 6  8]
 [10 13]]
Subtraction:
 [[-4 -4]
 [-4 -3]]
x multiplied by 2:
 [[ 2  4]
 [ 6 10]]
y multiplied by 3:
 [[15 18]
 [21 24]]
Square of x:
 [[ 1  4]
 [ 9 25]]
Square of y:
 [[25 36]
 [49 64]]
Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
Concatenated x and y:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w:
 [[ 9 11]
 [10 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


problem :4


In [ ]:
import numpy as np

A = np.array([[3,4], [7,8]])
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print(I)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print(AB)
print(BA)

[[23 13]
 [51 29]]
[[36 44]
 [13 16]]


In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
AB_T = AB.T

B_T = B.T
A_T = A.T
BT_AT = np.dot(B_T, A_T)

print(AB_T)
print(BT_AT)

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


In [ ]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
b = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
x = np.dot(A_inv, b)
print(x)

[ 2.  1. -2.]


In [ ]:
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print(X)



[ 2.  1. -2.]


Experiment

In [ ]:
import numpy as np
import time

size = 1_000_000
matrix = 1000

list_a = list(range(size))
list_b = list(range(size))

start_time = time.time()
list_sum = [a + b for a, b in zip(list_a, list_b)]
add = time.time() - start_time
print(f"Python List Element-wise Addition Time: {add:.5f} seconds")


Python List Element-wise Addition Time: 0.19647 seconds


In [ ]:
np_a = np.array(list_a)
np_b = np.array(list_b)
start_time = time.time()
np_sum = np_a + np_b
np_add = time.time() - start_time
print(f"NumPy Array Element-wise Addition Time: {np_add:.5f} seconds")


NumPy Array Element-wise Addition Time: 0.00476 seconds


Element-wise Multiplication

In [ ]:
start_time = time.time()
list_product = [a * b for a, b in zip(list_a, list_b)]
mul = time.time() - start_time
print(f"Python List Element-wise Multiplication Time: {mul:.5f} seconds")



Python List Element-wise Multiplication Time: 0.10540 seconds


In [ ]:
start_time = time.time()
np_product = np_a * np_b
np_mul = time.time() - start_time
print(f"NumPy Array Element-wise Multiplication Time: {np_mul:.5f} seconds")


NumPy Array Element-wise Multiplication Time: 0.00315 seconds


Dot Product

In [ ]:
start_time = time.time()
dot_product = sum(a * b for a, b in zip(list_a, list_b))
dot = time.time() - start_time
print(f"Python List Dot Product Time: {dot:.5f} seconds")


Python List Dot Product Time: 0.20858 seconds


In [ ]:
start_time = time.time()
np_dot_product = np.dot(np_a, np_b)
np_dot = time.time() - start_time
print(f"NumPy Array Dot Product Time: {np_dot:.5f} seconds")



NumPy Array Dot Product Time: 0.00401 seconds


Matrix Multiplication

In [38]:
start_time = time.time()
mat_mul= time.time() - start_time
print(f"Python List Matrix Multiplication Time: {mat_mul:.5f} seconds")

matrix_a = np.random.rand(matrix, matrix)
matrix_b = np.random.rand(matrix, matrix)


start_time = time.time()
np_result = np.dot(matrix_a, matrix_b)
np_matrix = time.time() - start_time
print(f"NumPy Array Matrix Multiplication Time: {np_matrix:.5f} seconds")

Python List Matrix Multiplication Time: 0.00006 seconds
NumPy Array Matrix Multiplication Time: 0.07060 seconds
