In [ ]:
import numpy as np
empty_array = np.empty((2,2))
print (empty_array)

[[4.87143841e-310 0.00000000e+000]
 [6.58136995e-310 4.87067457e-310]]


In [ ]:
import numpy as np
ones_array = np.ones((4,2))
print ((ones_array))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np
filled_array = np.full((4,2),7,dtype=int)
print(filled_array)

[[7 7]
 [7 7]
 [7 7]
 [7 7]]


In [ ]:
import numpy as np
zeros_array = np.zeros_like(filled_array)
print(zeros_array)


[[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
import numpy as np
ones_array = np.ones_like(filled_array)
print(ones_array)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
import numpy as np
new_list = [1,2,3,4]
new_array = np.array(new_list)
print(new_array)

[1 2 3 4]


In [1]:
import numpy as np

original_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
ones_array = np.ones_like(original_array)
print(ones_array)

[[1 1 1]
 [1 1 1]]


In [4]:
new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print(numpy_array)

[1 2 3 4]


problem:2

In [5]:
import numpy as np
array_range = np.arange(10,50)
print(array_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
array_1d = np.arange(9)
matrix_3x3 = array_1d.reshape((3, 3))
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
import numpy as np
random_array = np.random.random(30)
mean_value = random_array.mean()
print(mean_value)

0.45704389172524923


In [9]:
random_array = np.random.rand(10, 10)
min_value = random_array.min()
max_value = random_array.max()
print(min_value, max_value)

0.017477283233742757 0.9995452520689551


In [10]:
zeros_array = np.zeros(10)
zeros_array[4] = 1
print(zeros_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [12]:
shape = (5,5)
array_2d = np.ones(shape, dtype=int)
array_2d[1:-1, 1:-1] = 0
print(array_2d)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [13]:
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [18]:
x = np.array([[1,2], [3,5]])
y = np.array([[5,6], [7,8]])
v = np.array([9,10])
w = np.array([11,12])
add_xy = x + y
add_vw = v + w

sub_xy = x - y
sub_vw = v - w

mult_xy = x * y
mult_vw = v * w

sq_x = x**2
sq_y = y**2

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)

problem :4


In [19]:
import numpy as np

A = np.array([[3,4], [7,8]])
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print(I)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [20]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print(AB)
print(BA)

[[23 13]
 [51 29]]
[[36 44]
 [13 16]]


In [21]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
AB_T = AB.T

B_T = B.T
A_T = A.T
BT_AT = np.dot(B_T, A_T)

print(AB_T)
print(BT_AT)

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


In [22]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
b = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
x = np.dot(A_inv, b)
print(x)

[ 2.  1. -2.]


In [23]:

A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
b = np.array([-1, -3, 9])


x = np.linalg.solve(A, b)

print(x)

[ 2.  1. -2.]
